name: farmconnect
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  bot_toast: ^4.1.0
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  web: any
  universal_html: ^2.2.4
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.20
  google_generative_ai: ^0.4.6
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.2.1
  intl: ^0.19.0
  supabase: ^1.1.0    
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - env.json
