// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtKxtowLoT2lxlyCdSCoOcl1y-ewoX7dk',
    appId: '1:153260278526:android:713e84459cf8e3c6481baf',
    messagingSenderId: '153260278526',
    projectId: 'farmconnect-9826b',
    storageBucket: 'farmconnect-9826b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBDZxnNIcFq0brTLOZkYyzvaCPEGMxrw',
    appId: '1:153260278526:ios:33442382fa4ed87f481baf',
    messagingSenderId: '153260278526',
    projectId: 'farmconnect-9826b',
    storageBucket: 'farmconnect-9826b.firebasestorage.app',
    iosBundleId: 'com.farmconnect.app.testProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsfVYLiTdWDdCBRdD5q2vQmJnHFVXtNP4',
    appId: '1:153260278526:web:32179b13e99d14a1481baf',
    messagingSenderId: '153260278526',
    projectId: 'farmconnect-9826b',
    authDomain: 'farmconnect-9826b.firebaseapp.com',
    storageBucket: 'farmconnect-9826b.firebasestorage.app',
    measurementId: 'G-9QLWJYS9H7',
  );

}